# -*- coding: utf-8 -*-
"""Clase1FisicaComputacional.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1lEZNSYexFuE1CGyjtjQLptL4UA1ptd
"""

import numpy as np
import matplotlib.pyplot as plt

print(np.pi)

def convert_TF(Tc):
  return 9.0/5.0 * Tc +32.0

convert_TF(-40)

m = [1.0,2.0,3.0,6.0,9.0,11.] # masas
V = [0.13,0.26,0.50,0.77,1.15,1.36] # Volumen



plt.plot(m, V) # linea

plt.scatter(m, V, color='red', s=200, marker='p')
plt.plot(m,V, alpha=0.8, ls='--')
plt.title('Volumen vs Masa', size=30, color='green')
plt.xlabel('Masa (Kg)', size=10) # pasa textp y pone un label al eje
plt.ylabel('Volumen (L)', size= 10)